/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptScreenIdRouteImport } from './routes/prompt.$screenId'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as PromptSessionSessionIdRouteImport } from './routes/prompt.session.$sessionId'

const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptScreenIdRoute = PromptScreenIdRouteImport.update({
  id: '/$screenId',
  path: '/$screenId',
  getParentRoute: () => PromptRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSessionSessionIdRoute = PromptSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => PromptRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/prompt': typeof PromptRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/prompt/$screenId': typeof PromptScreenIdRoute
  '/prompt/session/$sessionId': typeof PromptSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/prompt': typeof PromptRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/prompt/$screenId': typeof PromptScreenIdRoute
  '/prompt/session/$sessionId': typeof PromptSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/prompt': typeof PromptRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/prompt/$screenId': typeof PromptScreenIdRoute
  '/prompt/session/$sessionId': typeof PromptSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/login'
    | '/prompt'
    | '/oauth/callback'
    | '/prompt/$screenId'
    | '/prompt/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/login'
    | '/prompt'
    | '/oauth/callback'
    | '/prompt/$screenId'
    | '/prompt/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/login'
    | '/prompt'
    | '/oauth/callback'
    | '/prompt/$screenId'
    | '/prompt/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PromptRoute: typeof PromptRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$screenId': {
      id: '/prompt/$screenId'
      path: '/$screenId'
      fullPath: '/prompt/$screenId'
      preLoaderRoute: typeof PromptScreenIdRouteImport
      parentRoute: typeof PromptRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/session/$sessionId': {
      id: '/prompt/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/prompt/session/$sessionId'
      preLoaderRoute: typeof PromptSessionSessionIdRouteImport
      parentRoute: typeof PromptRoute
    }
  }
}

interface PromptRouteChildren {
  PromptScreenIdRoute: typeof PromptScreenIdRoute
  PromptSessionSessionIdRoute: typeof PromptSessionSessionIdRoute
}

const PromptRouteChildren: PromptRouteChildren = {
  PromptScreenIdRoute: PromptScreenIdRoute,
  PromptSessionSessionIdRoute: PromptSessionSessionIdRoute,
}

const PromptRouteWithChildren =
  PromptRoute._addFileChildren(PromptRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PromptRoute: PromptRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
